server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**

      default-filters:
        - StripPrefix=1
